"""
xgboost_gatekeeper.py
======================
Green-Ops Framework — XGBoost Gatekeeper

Full pipeline:
  1. Receives impact analysis payload (generated externally via LLM)
  2. Cosine similarity computed between changed module embeddings and
     ALL test suite embeddings
  3. XGBoost Gatekeeper trained on presubmit_clean.csv + postsubmit_clean.csv
     predicts Probability of Failure (Pf) for each (module, test) pair
  4. Pruning decision: run test if Pf > threshold, skip otherwise

Dependencies:
    pip install xgboost pandas numpy scikit-learn
"""

import json
import logging
import os
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score

# If you need to test the pipeline end-to-end, import the LLM analyzer
from src.ai.llm_agent import LLMImpactAnalyzer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("greenops.gatekeeper")


# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

# Dataset available at: https://www.kaggle.com/datasets/akshyaaa/xgboost-pruning-dataset-based-on-historic-failure
PRESUBMIT_CSV        = os.environ.get("PRESUBMIT_CSV",  "presubmit_clean.csv")
POSTSUBMIT_CSV       = os.environ.get("POSTSUBMIT_CSV", "postsubmit_clean.csv")
PF_THRESHOLD         = float(os.environ.get("PF_THRESHOLD", "0.35"))
OUTPUT_DIR           = Path(os.environ.get("GREENOPS_OUTPUT", "./greenops_output"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# XGBoost hyperparameters — tuned for imbalanced CI failure datasets
XGBOOST_PARAMS = {
    "n_estimators":     400,
    "max_depth":        6,
    "learning_rate":    0.05,
    "subsample":        0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 3,
    "gamma":            0.1,
    "reg_alpha":        0.1,
    "reg_lambda":       1.0,
    "use_label_encoder": False,
    "eval_metric":      "logloss",
    "random_state":     42,
    # scale_pos_weight set dynamically from class balance
}


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — FEATURE ENGINEERING FROM PRE/POST SUBMIT DATASETS
# ─────────────────────────────────────────────────────────────────────────────

# These are the features generated by preprocess_submit_datasets.py
# The gatekeeper uses ALL numeric features, not just similarity + change_size
FEATURE_COLUMNS = [
    # From preprocessing pipeline
    "test_duration",
    "duration_log",
    "duration_zscore",
    "duration_normalized",
    "test_duration_mean",
    "test_duration_std",
    "test_duration_ratio",       # >1 = slower than usual (flakiness signal)
    "test_pass_rate",            # historical pass rate for this test
    "test_failure_rate",         # historical failure rate
    "test_total_runs",
    "test_total_failures",
    "test_flakiness_score",      # 0=stable, 1=maximally flaky
    "build_pass_rate",
    "build_test_count",
    "build_failure_count",
    "build_has_failure",
    "is_duration_outlier",
    # Test name semantic features
    "test_is_unit",
    "test_is_integration",
    "test_is_e2e",
    "test_is_perf",
    "test_is_smoke",
    "test_name_length",
    "test_name_depth",
    # Build path features
    "build_depth",
    "build_seg_0_enc",
    "build_seg_1_enc",
    "build_seg_2_enc",
    "build_seg_3_enc",
    # Added by gatekeeper from embeddings
    "cosine_similarity",         # GraphCodeBERT cosine sim: changed module vs test
    "change_size",               # lines added + deleted in PR diff
    "module_impact_score",       # LLM-derived: how directly is this module affected
    "is_kafka_consumer",         # 1 if test covers a Kafka consumer of changed topic
    "is_kafka_producer",         # 1 if test covers a Kafka producer of changed topic
    "is_shared_db",              # 1 if test shares a DB schema with changed module
    "is_frontend_contract",      # 1 if test validates an API contract used by frontend
    "is_shared_utility",         # 1 if test uses a shared utility that was changed
    "transitive_depth",          # how many hops away in the dependency graph
]

TARGET_COLUMN = "test_result"   # 1=PASSED, 0=FAILED (label to predict)
# We INVERT this for Pf: Pf = P(test_result=0) = P(FAILED)


def load_and_merge_datasets(
    presubmit_path: str,
    postsubmit_path: str,
) -> pd.DataFrame:
    """
    Load and merge presubmit_clean.csv + postsubmit_clean.csv.
    The postsubmit dataset is the ground truth for training since it
    records what actually passed or failed after the code was merged.
    The presubmit dataset provides the historical feature context.
    """
    frames = []

    for path, label in [(presubmit_path, "pre"), (postsubmit_path, "post")]:
        if not Path(path).exists():
            log.warning("%s not found — skipping", path)
            continue
        df = pd.read_csv(path, low_memory=False)
        df["dataset_source"] = label
        frames.append(df)
        log.info("Loaded %s: %d rows", label, len(df))

    if not frames:
        raise FileNotFoundError(
            "Neither presubmit_clean.csv nor postsubmit_clean.csv found. "
            "Run preprocess_submit_datasets.py first."
        )

    merged = pd.concat(frames, ignore_index=True)

    # Encode dataset source
    merged["is_postsubmit"] = (merged["dataset_source"] == "post").astype(int)

    log.info("Merged dataset: %d rows", len(merged))
    return merged


def prepare_features(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """
    Select and prepare feature matrix X and target y.
    Fills missing embedding-derived columns with 0 (they'll be populated
    at inference time from the LLM impact analysis + cosine similarity).
    """
    # Add missing embedding-derived columns with 0 defaults
    embedding_cols = [
        "cosine_similarity", "change_size", "module_impact_score",
        "is_kafka_consumer", "is_kafka_producer", "is_shared_db",
        "is_frontend_contract", "is_shared_utility", "transitive_depth",
    ]
    for col in embedding_cols:
        if col not in df.columns:
            df[col] = 0.0

    # Select only columns that exist in the dataframe
    available_features = [c for c in FEATURE_COLUMNS if c in df.columns]
    missing = set(FEATURE_COLUMNS) - set(available_features)
    if missing:
        log.debug("Feature columns not in dataset (will use 0): %s", missing)

    X = df[available_features].fillna(0)
    y = df[TARGET_COLUMN] if TARGET_COLUMN in df.columns else pd.Series(
        np.ones(len(df), dtype=int)
    )

    # INVERT: model predicts P(failure), but test_result=1 means PASSED
    # So we train on y_failure = 1 - test_result
    y_failure = 1 - y.astype(int)

    return X, y_failure, available_features


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — COSINE SIMILARITY ENGINE
# Computes similarity between changed module GraphCodeBERT embeddings
# and test suite embeddings
# ─────────────────────────────────────────────────────────────────────────────

class EmbeddingSimilarityEngine:
    """
    Computes cosine similarity between changed module embeddings
    (from your graphcodebert_embeddings module) and test embeddings.
    """

    def compute_similarity_matrix(
        self,
        changed_embeddings: dict[str, np.ndarray],   # {module_hash: embedding_vector}
        test_embeddings:    dict[str, np.ndarray],   # {test_name:   embedding_vector}
    ) -> pd.DataFrame:
        """
        Returns a DataFrame with columns:
            module_hash | test_name | cosine_similarity
        One row per (module, test) pair.
        """
        if not changed_embeddings or not test_embeddings:
            log.warning("Empty embeddings passed to similarity engine")
            return pd.DataFrame(columns=["module_hash", "test_name", "cosine_similarity"])

        module_hashes = list(changed_embeddings.keys())
        test_names    = list(test_embeddings.keys())

        # Stack into matrices for vectorized cosine computation
        mod_matrix  = np.vstack([changed_embeddings[h] for h in module_hashes])
        test_matrix = np.vstack([test_embeddings[t]    for t in test_names])

        # Shape: (n_modules, n_tests)
        sim_matrix = cosine_similarity(mod_matrix, test_matrix)

        # Flatten into rows
        rows = []
        for i, mod_hash in enumerate(module_hashes):
            for j, test_name in enumerate(test_names):
                rows.append({
                    "module_hash":       mod_hash,
                    "test_name":         test_name,
                    "cosine_similarity": float(sim_matrix[i, j]),
                })

        df = pd.DataFrame(rows)
        log.info("Computed %d (module, test) similarity pairs", len(df))
        return df

    def get_max_similarity_per_test(
        self,
        similarity_df: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        For each test, get the maximum similarity across all changed modules.
        This is the signal: if ANY changed module is semantically similar
        to the test, the test is relevant.
        """
        return (
            similarity_df
            .groupby("test_name")["cosine_similarity"]
            .max()
            .reset_index()
            .rename(columns={"cosine_similarity": "max_cosine_similarity"})
        )


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — XGBOOST GATEKEEPER
# ─────────────────────────────────────────────────────────────────────────────

class XGBoostGatekeeper:
    """
    Trained on presubmit + postsubmit historical data.
    Predicts Probability of Failure (Pf) for each (module, test) pair.
    Decision: run test if Pf > PF_THRESHOLD, prune otherwise.
    """

    def __init__(
        self,
        presubmit_path:  str = PRESUBMIT_CSV,
        postsubmit_path: str = POSTSUBMIT_CSV,
        pf_threshold:    float = PF_THRESHOLD,
    ):
        self.pf_threshold     = pf_threshold
        self.model            = None
        self.scaler           = StandardScaler()
        self.feature_columns  = []
        self.scale_pos_weight = 1.0
        self._train(presubmit_path, postsubmit_path)

    def _train(self, presubmit_path: str, postsubmit_path: str):
        """Train XGBoost on merged pre+post submit historical data."""
        try:
            df = load_and_merge_datasets(presubmit_path, postsubmit_path)
            X, y_failure, feat_cols = prepare_features(df)
            self.feature_columns = feat_cols

            # Compute class balance for scale_pos_weight
            n_pass   = (y_failure == 0).sum()
            n_fail   = (y_failure == 1).sum()
            if n_fail > 0:
                self.scale_pos_weight = n_pass / n_fail
                log.info("Class balance — Pass: %d  Fail: %d  scale_pos_weight: %.2f",
                         n_pass, n_fail, self.scale_pos_weight)

            # Train/val split (chronological order matters for CI data)
            X_train, X_val, y_train, y_val = train_test_split(
                X, y_failure, test_size=0.15, shuffle=False
            )

            # Scale features
            X_train_s = self.scaler.fit_transform(X_train)
            X_val_s   = self.scaler.transform(X_val)

            # Build model with dynamic scale_pos_weight
            params = {**XGBOOST_PARAMS, "scale_pos_weight": self.scale_pos_weight}
            self.model = xgb.XGBClassifier(**params)

            self.model.fit(
                X_train_s, y_train,
                eval_set=[(X_val_s, y_val)],
                verbose=False,
            )

            # Evaluate
            y_pred_proba = self.model.predict_proba(X_val_s)[:, 1]
            y_pred       = (y_pred_proba > self.pf_threshold).astype(int)

            auc = roc_auc_score(y_val, y_pred_proba)
            log.info("Gatekeeper trained — Val AUC: %.4f", auc)
            log.info("\n%s", classification_report(y_val, y_pred,
                                                   target_names=["pass", "fail"]))

            # Save model
            model_path = OUTPUT_DIR / "gatekeeper_model.json"
            self.model.save_model(str(model_path))
            log.info("Model saved -> %s", model_path)

        except Exception as exc:
            log.warning("Could not train on real data: %s — using mock model", exc)
            self._train_mock()

    def _train_mock(self):
        """Minimal mock training for testing without real data."""
        X_mock = np.array([
            [0.9, 10, 0.95, 0, 0, 0, 0, 0, 1],
            [0.2, 50, 0.10, 1, 0, 1, 0, 0, 2],
            [0.7, 20, 0.80, 0, 0, 0, 1, 0, 1],
            [0.1, 80, 0.05, 0, 1, 1, 0, 0, 3],
            [0.5, 30, 0.60, 1, 1, 0, 0, 1, 2],
            [0.8, 15, 0.90, 0, 0, 0, 0, 0, 1],
            [0.3, 60, 0.20, 1, 0, 1, 1, 0, 2],
        ])
        y_mock = np.array([0, 1, 0, 1, 1, 0, 1])
        self.feature_columns = [
            "cosine_similarity", "change_size", "module_impact_score",
            "is_kafka_consumer", "is_kafka_producer", "is_shared_db",
            "is_frontend_contract", "is_shared_utility", "transitive_depth",
        ]
        X_scaled = self.scaler.fit_transform(X_mock)
        self.model = xgb.XGBClassifier(**{**XGBOOST_PARAMS, "n_estimators": 50})
        self.model.fit(X_scaled, y_mock)
        log.info("Mock gatekeeper trained (replace with real data)")

    def load_pretrained(self, model_path: str):
        """Load a previously saved model instead of retraining."""
        self.model = xgb.XGBClassifier()
        self.model.load_model(model_path)
        log.info("Loaded pretrained model from %s", model_path)

    def predict_failure_prob(self, feature_vector: dict) -> float:
        """
        Predict Probability of Failure for a single (module, test) pair.

        Args:
            feature_vector: dict with keys matching self.feature_columns
                {
                  "cosine_similarity": 0.82,
                  "change_size": 45,
                  "module_impact_score": 0.9,
                  "is_kafka_consumer": 0,
                  "is_kafka_producer": 1,
                  "is_shared_db": 1,
                  "is_frontend_contract": 0,
                  "is_shared_utility": 0,
                  "transitive_depth": 2,
                  "test_flakiness_score": 0.1,
                  ... all other features
                }

        Returns:
            float: Pf (0.0 = definitely passes, 1.0 = definitely fails)
        """
        row = np.array([[feature_vector.get(col, 0.0)
                         for col in self.feature_columns]])
        row_scaled = self.scaler.transform(row)
        pf = float(self.model.predict_proba(row_scaled)[0][1])
        return pf

    def predict_batch(self, feature_df: pd.DataFrame) -> np.ndarray:
        """
        Batch predict Pf for a DataFrame of feature rows.
        Returns array of Pf values.
        """
        cols  = [c for c in self.feature_columns if c in feature_df.columns]
        X     = feature_df[cols].fillna(0).values
        X_s   = self.scaler.transform(X)
        return self.model.predict_proba(X_s)[:, 1]

    def get_feature_importance(self) -> pd.DataFrame:
        """Return feature importance for interpretability."""
        importance = self.model.feature_importances_
        return (
            pd.DataFrame({
                "feature":    self.feature_columns,
                "importance": importance,
            })
            .sort_values("importance", ascending=False)
            .reset_index(drop=True)
        )


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — PRUNING DECISION ENGINE
# Combines external LLM impact + cosine similarity + XGBoost Pf into final decision
# ─────────────────────────────────────────────────────────────────────────────

class PruningDecisionEngine:
    """
    Orchestrates the full pipeline:
      Impact payload → cosine similarity → XGBoost Pf → prune/run decision
    """

    def __init__(
        self,
        gatekeeper:         XGBoostGatekeeper,
        similarity_engine:  EmbeddingSimilarityEngine,
        pf_threshold:       float = PF_THRESHOLD,
    ):
        self.gatekeeper        = gatekeeper
        self.similarity_engine = similarity_engine
        self.pf_threshold      = pf_threshold

    def decide(
        self,
        impact_result:          dict,                # Passed in from external LLM Analyzer
        changed_embeddings:     dict[str, np.ndarray],  # {hash: vector} from GraphCodeBERT
        test_embeddings:        dict[str, np.ndarray],  # {test_name: vector}
        historical_test_stats:  pd.DataFrame,        # from presubmit_clean.csv
        change_size:            int = 0,             # total lines changed in PR
    ) -> dict:
        """
        Full pruning decision for a PR.

        Returns:
            {
              "run":   [list of test names to execute],
              "prune": [list of test names to skip],
              "pf_scores": {test_name: Pf},
              "impact_analysis": {...},
              "reasoning": {...}
            }
        """

        # ── Step 1: Parse affected module hashes from external LLM dict ────────
        log.info("Step 1: Parsing impact analysis payload ...")
        impact = impact_result
        affected_hashes = set(impact.get("affected_module_hashes", []))

        # Build impact metadata lookup
        impact_meta = {
            item["module_hash"]: item
            for item in impact.get("impact_analysis", [])
        }

        # ── Step 2: Cosine similarity (changed modules vs tests) ──────────────
        log.info("Step 2: Computing cosine similarity ...")

        # Filter embeddings to affected modules only
        affected_embeddings = {
            h: v for h, v in changed_embeddings.items()
            if h in affected_hashes
        }
        if not affected_embeddings:
            affected_embeddings = changed_embeddings  # fallback

        sim_df = self.similarity_engine.compute_similarity_matrix(
            affected_embeddings, test_embeddings
        )
        max_sim = self.similarity_engine.get_max_similarity_per_test(sim_df)

        # ── Step 3: Build feature matrix for XGBoost ─────────────────────────
        log.info("Step 3: Building feature matrix for XGBoost ...")

        # Merge similarity with historical test stats
        test_stats = historical_test_stats.copy() if historical_test_stats is not None \
                     else pd.DataFrame()

        feature_rows = []
        for _, sim_row in max_sim.iterrows():
            test_name = sim_row["test_name"]
            cos_sim   = sim_row["max_cosine_similarity"]

            # Get historical stats for this test
            hist = {}
            if not test_stats.empty and "test_name" in test_stats.columns:
                match = test_stats[test_stats["test_name"] == test_name]
                if not match.empty:
                    hist = match.iloc[0].to_dict()

            # Get impact metadata from LLM
            # Find impact for the most similar module
            best_module = (
                sim_df[sim_df["test_name"] == test_name]
                .sort_values("cosine_similarity", ascending=False)
                .iloc[0]["module_hash"] if not sim_df[sim_df["test_name"] == test_name].empty
                else ""
            )
            meta = impact_meta.get(best_module, {})
            impact_type     = meta.get("impact_type", "none")
            transitive_depth = meta.get("transitive_depth", 0)
            llm_confidence  = meta.get("confidence", 0.0)

            feature_rows.append({
                "test_name":              test_name,
                "cosine_similarity":      cos_sim,
                "change_size":            change_size,
                "module_impact_score":    llm_confidence,
                "is_kafka_consumer":      int(impact_type == "kafka_consumer"),
                "is_kafka_producer":      int(impact_type == "kafka_producer"),
                "is_shared_db":           int(impact_type == "shared_db"),
                "is_frontend_contract":   int(impact_type == "frontend_contract"),
                "is_shared_utility":      int(impact_type == "shared_utility"),
                "transitive_depth":       transitive_depth,
                # Historical features from preprocessed dataset
                "test_duration":          hist.get("test_duration", 0),
                "duration_log":           hist.get("duration_log", 0),
                "duration_normalized":    hist.get("duration_normalized", 0),
                "test_duration_ratio":    hist.get("test_duration_ratio", 1.0),
                "test_pass_rate":         hist.get("test_pass_rate", 1.0),
                "test_failure_rate":      hist.get("test_failure_rate", 0.0),
                "test_flakiness_score":   hist.get("test_flakiness_score", 0.0),
                "test_total_runs":        hist.get("test_total_runs", 0),
                "test_total_failures":    hist.get("test_total_failures", 0),
                "build_pass_rate":        hist.get("build_pass_rate", 1.0),
                "build_has_failure":      hist.get("build_has_failure", 0),
                "test_is_unit":           hist.get("test_is_unit", 0),
                "test_is_integration":    hist.get("test_is_integration", 0),
                "test_is_e2e":            hist.get("test_is_e2e", 0),
                "test_name_depth":        hist.get("test_name_depth", 1),
                "build_depth":            hist.get("build_depth", 1),
            })

        feat_df = pd.DataFrame(feature_rows)

        # ── Step 4: XGBoost batch prediction ─────────────────────────────────
        log.info("Step 4: XGBoost Pf prediction for %d tests ...", len(feat_df))
        if not feat_df.empty:
            pf_scores = self.gatekeeper.predict_batch(feat_df)
            feat_df["pf_score"] = pf_scores
        else:
            feat_df["pf_score"] = 0.0

        # ── Step 5: Prune/run decision ────────────────────────────────────────
        run_tests   = feat_df[feat_df["pf_score"] >= self.pf_threshold]["test_name"].tolist()
        prune_tests = feat_df[feat_df["pf_score"] <  self.pf_threshold]["test_name"].tolist()

        pf_dict = dict(zip(feat_df["test_name"], feat_df["pf_score"].round(4)))

        log.info(
            "Pruning decision — Run: %d  Prune: %d  (threshold=%.2f)",
            len(run_tests), len(prune_tests), self.pf_threshold
        )

        # Save decision artifact
        result = {
            "run":             run_tests,
            "prune":           prune_tests,
            "pf_scores":       pf_dict,
            "total_tests":     len(feat_df),
            "pruning_rate":    round(len(prune_tests) / max(len(feat_df), 1), 3),
            "pf_threshold":    self.pf_threshold,
            "impact_analysis": impact,
            "reasoning": {
                "affected_modules":        list(affected_hashes),
                "kafka_topics":            impact.get("kafka_topics_affected", []),
                "db_tables":               impact.get("shared_db_tables_affected", []),
                "frontend_contracts":      impact.get("frontend_contracts_affected", []),
                "llm_summary":             impact.get("summary", ""),
            },
        }

        decision_path = OUTPUT_DIR / "pruning_decision.json"
        with open(decision_path, "w") as f:
            json.dump(result, f, indent=2)
        log.info("Pruning decision saved -> %s", decision_path)

        return result


# ─────────────────────────────────────────────────────────────────────────────
# EXAMPLE USAGE / INTEGRATION POINT
# ─────────────────────────────────────────────────────────────────────────────

def run_gatekeeper_pipeline(
    changed_modules:    list[dict],
    module_registry:    list[dict],
    changed_embeddings: dict[str, np.ndarray],
    test_embeddings:    dict[str, np.ndarray],
    change_size:        int = 0,
) -> dict:
    """
    Single entry point called by github_ci_integration.py after:
      - ast_parser.py has parsed the diff
      - module_db.py has generated hashes
      - graphcodebert_embeddings.py has generated embeddings

    Args:
        changed_modules:    output from module_db.py (list of module dicts with hashes)
        module_registry:    all modules in codebase (from your DB/S3)
        changed_embeddings: {module_hash: np.ndarray} from GraphCodeBERT
        test_embeddings:    {test_name:   np.ndarray} from GraphCodeBERT
        change_size:        total lines changed in the PR

    Returns:
        pruning decision dict with run/prune lists and Pf scores
    """
    
    # ── [NEW]: Generate impact externally first via the newly decoupled LLM module
    log.info("Orchestrating pipeline: Fetching LLM Impact Analysis first...")
    analyzer = LLMImpactAnalyzer()
    impact_result = analyzer.analyze_impact(changed_modules, module_registry)

    # Load historical test stats for feature engineering
    historical_stats = None
    for path in [PRESUBMIT_CSV, POSTSUBMIT_CSV]:
        if Path(path).exists():
            historical_stats = pd.read_csv(path, low_memory=False)
            break

    gatekeeper       = XGBoostGatekeeper()
    similarity_engine = EmbeddingSimilarityEngine()

    engine = PruningDecisionEngine(
        gatekeeper=gatekeeper,
        similarity_engine=similarity_engine,
    )

    return engine.decide(
        impact_result=impact_result,
        changed_embeddings=changed_embeddings,
        test_embeddings=test_embeddings,
        historical_test_stats=historical_stats,
        change_size=change_size,
    )


if __name__ == "__main__":
    # ── Smoke test with mock data ─────────────────────────────────────────────
    log.info("Running smoke test with mock data ...")

    mock_changed = [
        {
            "module_hash":   "abc123",
            "filepath":      "src/payments/PaymentService.java",
            "language":      "java",
            "imports":       ["com.example.db.PaymentRepo", "com.example.kafka.PaymentProducer"],
            "db_tables":     ["payments", "transactions"],
            "kafka_topics":  ["payment-events"],
            "kafka_role":    "producer",
            "api_endpoints": ["POST /api/v1/payments"],
            "is_frontend":   False,
        }
    ]

    mock_registry = mock_changed + [
        {
            "module_hash":   "def456",
            "filepath":      "src/notifications/NotificationConsumer.java",
            "imports":       ["com.example.kafka.PaymentConsumer"],
            "db_tables":     [],
            "kafka_topics":  ["payment-events"],
            "kafka_role":    "consumer",
            "api_endpoints": [],
            "is_frontend":   False,
        },
        {
            "module_hash":   "ghi789",
            "filepath":      "frontend/src/components/PaymentForm.tsx",
            "imports":       [],
            "db_tables":     [],
            "kafka_topics":  [],
            "kafka_role":    "",
            "api_endpoints": ["POST /api/v1/payments"],
            "is_frontend":   True,
        },
    ]

    dim = 128
    mock_changed_emb = {"abc123": np.random.rand(dim)}
    mock_test_emb    = {
        "PaymentServiceTest":      np.random.rand(dim),
        "NotificationConsumerTest": np.random.rand(dim),
        "PaymentFormTest":         np.random.rand(dim),
        "UserServiceTest":         np.random.rand(dim),
    }

    result = run_gatekeeper_pipeline(
        changed_modules=mock_changed,
        module_registry=mock_registry,
        changed_embeddings=mock_changed_emb,
        test_embeddings=mock_test_emb,
        change_size=45,
    )

    print("\n" + "=" * 60)
    print("PRUNING DECISION")
    print("=" * 60)
    print(f"  Tests to RUN   ({len(result['run'])}): {result['run']}")
    print(f"  Tests to PRUNE ({len(result['prune'])}): {result['prune']}")
    print(f"  Pruning rate   : {result['pruning_rate']:.1%}")
    print(f"  Pf scores      : {result['pf_scores']}")
    print(f"  Kafka topics   : {result['reasoning']['kafka_topics']}")
    print(f"  DB tables      : {result['reasoning']['db_tables']}")
    print(f"  LLM summary    : {result['reasoning']['llm_summary']}")

class Gatekeeper(PruningDecisionEngine):
    """
    Backward-compatible wrapper for old DecisionEngine.
    """

    def __init__(self):
        gatekeeper_model = XGBoostGatekeeper()
        similarity_engine = EmbeddingSimilarityEngine()

        super().__init__(
            gatekeeper=gatekeeper_model,
            similarity_engine=similarity_engine,
        )

    def predict_failure_prob(self, similarity, change_size):
        """
        Legacy API expected by decision_engine.py
        Returns probability score.
        """
        # Map simple parameters to the feature dictionary expected by XGBoostGatekeeper
        feature_dict = {
            "cosine_similarity": float(similarity),
            "change_size": float(change_size),
            "module_impact_score": 0.5,  # neutral default
            "transitive_depth": 1,
        }

        try:
            # Use the underlying XGBoostGatekeeper's prediction logic (which handles scaling)
            return self.gatekeeper.predict_failure_prob(feature_dict)
        except Exception as e:
            log.warning("Gatekeeper prediction failed: %s — falling back to heuristic", e)
            # heuristic fallback
            risk = (1 - similarity) * 0.6 + min(change_size / 100.0, 1.0) * 0.4
            return float(max(0.0, min(risk, 1.0)))